DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS tags;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE photos(
  photo_id SERIAL PRIMARY KEY,
  photo_path TEXT NOT NULL,
  user_id  INTEGER UNIQUE NOT NULL,
  tag_id  INTERGER UNIQUE,
  FOREIGN KEY (user_id) REFERENCES user(id),
  FOREIGN KEY (tag_id) REFERENCES tags(tag_id)

);

CREATE TABLE tags(
  tag_id SERIAL PRIMARY KEY,
  tag TEXT NOT NULL,
  user_id INTEGER UNIQUE NOT NULL,
  foto_id INTEFER UNIQUE NOT NULL,
  FOREIGN KEY(foto_id) REFERENCES photos(photo_id),
  FOREIGN KEY (user_id) REFERENCES user(id)

  
);
